### ISSUE TITLE
Windows installer shows default Bitcoin path for destination folder.

### ISSUE THREAD

**Issue by TechAdeptRDD** [reddcoin-project/reddcoin#1]
Windows installer shows default Bitcoin path for destination folder. Should be Program Files/ReddCoin, not Bitcoin
![wrongpath](https://user-images.githubusercontent.com/39470203/159730534-c3ee74ca-aa77-4bbd-8f16-028335ac3aa5.png)
.

**Comment by reddink** [comment]
Identified, and resolved the path setting

**Comment by reddink** [comment]
@TechAdeptRDD 

on the next build pass, could you test uninstalling, the reinstalling

**Comment by reddink** [comment]
Should have been resolved in commit 3ec662eb
Moved to testing
