### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by aleex5** [reddcoin-project/reddcoin#58]
I would love it if you could add in the configuration options the option to activate a dark mode.

**Comment by reddink** [comment]
Would you like this to be working per app, or as a part of the OS?
That is, if the OS is set to dark mode, then the GUI will also?
Or, to be able to select  the option within the app?

**Comment by aleex5** [comment]
there are applications that detect the dark mode of the operating system, but if the user wants to change the theme, it still allows it.

**Comment by aleex5** [comment]
> ¿Le gustaría que esto funcione por aplicación o como parte del sistema operativo? Es decir, si el sistema operativo está configurado en modo oscuro, ¿la GUI también lo hará? ¿O para poder seleccionar la opción dentro de la aplicación?

I think both ways are useful, I have seen applications that automatically detect the dark mode, but still give an option for the user to set it manually.

**Comment by aleex5** [comment]
I think both ways are useful, I have seen applications that automatically detect the dark mode, but still give an option for the user to set it manually.

example:
![Sin título](https://github.com/reddcoin-project/reddcoin-0.22/assets/35360938/604ce14a-d1cd-495b-946e-924042368c07)

**Comment by apilypas** [comment]
I have seen it to work nicely on linux KDE desktop environments when built from source - from global theme integration. I think it should not take much time to implement dark theme adoptation for QT based programs (as core wallet is) for other operating systems.

I checked many spots on wallet with global dark theme (KDE) and I think it looks great there, except one spot:
![image](https://github.com/reddcoin-project/reddcoin-0.22/assets/39899835/429e02c6-500b-47c9-82c0-a8a02732692e)

**Comment by reddink** [comment]
Staking view is missing the 'PlatformStyle' from the code that displays the page.
Will need to refactor this so as to help enable correct display
