### ISSUE TITLE
Corrupted Block Database After Each Use 

### ISSUE THREAD

**Issue by ReddyFreddy** [reddcoin-project/reddcoin#6]
Alpha 2
Windows 7

I can only use the wallet one time before having to delete the blockchain and download it all over again:

Corrupted block database detected

Do you want to rebuild the block database now?
OK

Error: Error opening block database

**Comment by reddink** [comment]
Could you please attach debug.log for analysis.

**Comment by ReddyFreddy** [comment]
Sorry, I deleted the debug and now I haven't been able to recreate the issue. Will post if it happens again. It was happening with each run until now.

**Comment by barrystyle** [comment]
Windows 7 32/64bit
Under a virtual machine?
Any other information... at all?

Given the amount of issues you've posted, i'd recommend you get your machine checked out.. considering its resolved itself

**Comment by ReddyFreddy** [comment]
Win 7 64
no virtual machine
👋🍆

**Comment by ReddyFreddy** [comment]
> Windows 7 32/64bit Under a virtual machine? Any other information... at all?

Win 7 64
no virtual machine

> Given the amount of issues you've posted, i'd recommend you get your machine checked out.. considering its resolved itself

👋 🍆

**Comment by ReddyFreddy** [comment]
[debug.log](https://github.com/reddcoin-project/reddcoin-0.22/files/8493902/debug.log)


> Could you please attach debug.log for analysis.
[debug.log](https://github.com/reddcoin-project/reddcoin-0.22/files/8493903/debug.log)

**Comment by ReddyFreddy** [comment]
> Could you please attach debug.log for analysis.

[debug.log](https://github.com/reddcoin-project/reddcoin-0.22/files/8493906/debug.log)

**Comment by barrystyle** [comment]
@ReddyFreddy I'm only able to replicate this by shutting client down, deleting 'blocks' or 'chainstate' in testnet3 folder (not both) and then starting client again. There are very few differences between bitcoin and our code in this area (checking and retrieving state from disk). Are you able to confirm that the testnet3 folder is being fully deleted, before you go to start the client again in the case of a resync?

**Comment by barrystyle** [comment]
Resolved in https://github.com/reddcoin-project/reddcoin-0.22/commit/1e0e3b60d6c074a8fbc60654e1f07830b9237458, pending further testing.

**Comment by barrystyle** [comment]
Merged into develop in https://github.com/reddcoin-project/reddcoin-0.22/pull/16
